### ISSUE TITLE
Create project plan for 2023

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/meetup#3]
Relevant (O)KRs:
OKR1: Grow the global meetup community
KR1.1: 5k people meeting up every month by the end of 2023
KR1.2: 100 meetup communities by the end of 2023.
KR1.3: 100% of our meetup groups have held at least one meetup in the last 3 months

Draft GSF roadmap for 2023:
Q2 Earth Week & Summit (?)
Q3 TEDx & OS Summit (?)
Q4 CarbonHack23 & Cop28

Official roadmap announced in the Annual Report at the end of January
<img width="763" alt="roadmap 2023" src="https://user-images.githubusercontent.com/100846607/216055608-4c884924-0f1b-4c89-b44c-211bcc015fdd.png">

**Comment by tadanna** [comment]
@holanita as this is related to events and meetup, I believe it would make sense to keep this info in the Meetup folder. Perhaps we can transform [this](https://docs.google.com/document/d/1eSCxQPfFGBpEtaX2hm-Spy_-cd31lYs2dnAxO-wT23Q/edit) roadmap into a slide (using the GSF template [here](https://docs.google.com/presentation/d/1U4T1W-d6j9HMTXhYd4d1UKNstjn4SHJFET6ZMVFmros/edit#slide=id.g100b8d1b9c5_0_22)) and include: 

- the OKRs for 2023
- events expected in the different Qs

This could be mentioned in the guideline so that organisers also always have access to it. I would say for the future, when the Wikis are published and available to everyone, maybe we can move these information there without having a document?

 Topics such as events frequency, difference between Flagship vs Community and event types should be available internally and for organisers - so we can find in the existing documents where (and if) it makes sense to explicitly state these information.

**Comment by holanita** [comment]
@tadanna as also discussed on the call, let's use the screenshot from the annual report for now. and it was decided yesterday that soon we will start using the wiki instead of the google drive so let's try to avoid sharing the folder with anyone from now on. we can share PDFs for now and we'll share the WIKI when it's ready.

just to be saved, I've deleted your roadmap doc as it wasn't entirely up-to-date. this is what we can officially communicate.
<img width="788" alt="Screenshot 2023-02-01 at 11 03 41" src="https://user-images.githubusercontent.com/100846607/216054181-b7c8b10b-af21-4210-84a7-b78deb835e4e.png">

**Comment by tadanna** [comment]
@holanita can we start to do this directly on Wiki then? Anybody with access to it could already see it, and for who doesn't have access yet, it's possible to export the Wiki pages in PDF. I believe this makes it a bit easier and we don't need to move it later on. We could create a child page under the Meetup one.

**Comment by tadanna** [comment]
@holanita yes maybe I will start to move it to Wiki. If there are any changes we can make them directly there, so that we can completely discard the google doc - we can export the Wiki page any time we need to share it with someone that doesn't have access. Is it ok too create a "child page" under the "community WG" one?

**Comment by tadanna** [comment]
@holanita I have included the roadmap at the end of the page - I haven't included the image as it's not updated. 
I would like to include links to documents / future events so that people can refer back to it, but I cannot find the annual report on the website...could you drop the link here?

**Comment by jawache** [comment]
Hia, just want to make sure we are on the same page about this now (I feel there has been a lot of confusion about this in the past). The meetup project is **just** the meetup project, as in getting meetup events/groups launched on meetup.com. The other things listed in the wiki are their own separate projects, will likley be run by another PM or we might outsource completely to another agency, the roadmap for the meetup project is not to deliver the TEDx event for instance.
