### ISSUE TITLE
Meetup - Audit the groups

### ISSUE THREAD

**Issue by tadanna** [Green-Software-Foundation/meetup#31]
With the learnings from Q1 and Earth Week, audit all groups of Meetup. 
The purpose of this is to identify the groups that are not active. 

For the non-active groups see if we can find another organiser willing to step-in. 
If that is not possible, consider closing the Meetup group. 

@holanita  we will need to consider: 
- what happens to the members of the meetup group if we close it down? It would be a pity to loose them. 
- Should we give an indication to our organisers of our expectations? I.e. we want them to organise at least 2 events per year, or 1 every Q...

**Comment by jawache** [comment]
FYI @tadanna and @holanita to me this is just as important as the Q1 events, and a higher priority than any Earth Week planning. I listed it in the [Q1 goals ticket](https://github.com/Green-Software-Foundation/meetup/issues/21). Is there any reason we can't do this is parallel to the Q1 events? They are tightly related, in my ticket this was actually the first step :) 

FYI expectation is 1 event every month, we might accept 3 months of no events for holidays/exceptions etc... but 1 every month is normal in this space the OKRs reflect that.

I think the audit isn't something that will take a lot of PM time in my opinion. it will take a lot of real time but most of the time is waiting for people to respond but the actions on our side are relatively short, send a communication and wait for people to respond.

Copying and pasting this from the original ticket:

**Identify organizers for our existing groups**

- Let's work very hard to find organizers for the existing groups, because if we can't we should kill the group and stop paying for it.
- Who are the existing organizers? (it shows on meetup for each group)
- Do they actually want to continue organizing? (we did ask before, let's ask again)
- Add the people who've raised their hands in other Community WG meetings? (I believe they are listed in the doc)
- If we can't find anyone to organize of of our meetup groups we can send a message asking members of the meetup group if anyone else want's to organize that meetup group
- If we still need to find organizers for our meetup groups reach out to the broader public, newsletter etc...

To track this task I would suggest:

For every meetup group without at least one existing active organizer (one of the people in our list who have explicitly and recently volunteered to organize):
- [ ] Send an email to the existing organizers asking them if they want to stay on as organizers? There is a way in meetup to message the other organizers. If they want to be an organizer we expect an event in Q1 if not let's remove them.
- [ ] Send an email to the members of the meetup group. People who joined the group to go to events, someone there might actually be interested in organizing. Again you can message people from the meetup platform.
- [ ] I can send an email to gsf-all with list of groups missing leaders asking if anyone wants to volunteer to organize.
- [ ] We can send a few emails through our weekly newsletter with list of groups missing leaders asking if anyone wants to volunteer to organize.
- [ ] If we are still struggling at this point we can start posting on socials and I can start directly reaching out to member orgs with a strong presence in each of the regions with missing organizers.

**NOTE**: If you are volunteering to organize a group that has to come with a **commitment to run one in Q1**, otherwise people will just say yes and carry on doing nothing. We'll lose a lot of people with such as hard commitment but that's totally fine, I'd rather end up with 1 person who's actually willing and able to put in time than 5 people who are willing but can't really put the time in.

**Comment by jawache** [comment]
Thanks, and yes, we should do as many as we can. The 5 I mentioned was more of a min but there is no upper limit.

Our OKRs for this project are defined online [here](https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/3342524/Community+Meetup) the only way I see us meeting those targets is if we use Q1 to get ready, have a process, build up some experience and then Q2,3,4 is all about executing the same plan, regular monthly meetings, and growing number of groups and regions. 

If the limit is staffing/time we can augment with additional hires, the OKRs won't change. Those are the kinds of numbers I'll need to show our members for them to consider this project a success and worthwhile continuing to invest in.

**Comment by tadanna** [comment]
@jawache @holanita progress update here: 

- contacted the volunteers based on [this](https://github.com/Green-Software-Foundation/meetup/issues/5) task. Received some answers and waiting for some more. 
- I contacted few more people that were listed as "assistant organisers" in the meetup groups and for which I could find an email 

Everything is in [this](https://docs.google.com/spreadsheets/d/165Nu3mCrzYpIi2ua34TmSTdOWdFIkukN-oXyd3Fq9ZQ/edit#gid=0) file, but I want to add a tab that reviews the organisers **_by group_**, so that we can easily see where we miss one/where we need to double check availability and interest.

**Comment by tadanna** [comment]
@holanita this was two weeks ago. Last week I contacted a lot more people. I am moving in steps:

1. I contacted the people in the list you gave me
2. I got in touch with the organisers in the groups (the ones above didn't have any assigned)
3. I got in touch with all members in the groups that belong to a member org
4. I will get in touch with members in the groups that DON'T belong to member org (but I would wait for this, I think we are not t here yet)

Of the above, if I am not mistaken, only for Israel I couldn't find a contact. Let me know if you have one. 
Everything is updated [here](https://docs.google.com/spreadsheets/d/165Nu3mCrzYpIi2ua34TmSTdOWdFIkukN-oXyd3Fq9ZQ/edit#gid=0).
