### ISSUE TITLE
Custom graphics for GSF Northern Ireland

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/meetup#98]
Hi @Jenya-design, The organiser of GSF Northern Ireland @nevin243 has requested a custom meetup graphic. I have created an interim graphic for the group.

Please can we include *non political* graphics. 

Suggestions are: 

Giants Causeway
Belfast Cranes (Samson & Goliath)
Dunluce Castle
Derry Peace Bridge
The Big Fish [Belfast Sculpture]

Please can we maintain the typical green colour. The colours orange & red are not to be included. No flags.

Due date of 8 September

**Comment by adamj89** [comment]
| ------------- | ------------- |
| Group Name: | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by Jenya-design** [comment]
@adamj89 @Nevin243 please review the custom meetup graphic attached and [on Drive](https://drive.google.com/drive/folders/1Xp4R9JwqlHO0e7RoyhGcqKcmupoObyRU?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/14dfe2af-934a-4232-aba4-025fdb90593e)

Let me know if you need anything else

**Comment by adamj89** [comment]
Oh I love it! @Nevin243 what do you think?

**Comment by adamj89** [comment]
@Jenya-design great work Consider this approved once Marc gives his thoughts.

**Comment by Nevin243** [comment]
Sorry @adamj89 @Jenya-design, I had some unexpected personal commitments and only saw these notifications buried when I've been unwinding my emails! 

Love these! They look fantastic, love to get in on the meetup page and start sharing!

Only query would be the pillars/rocks, would we be able to get a slight edit? Only, if it's not massive amounts of effort? They're normally depicted as hexagons (we use them for everything here because they're so distinct), here's a close-up [reference](https://en.wikipedia.org/wiki/Giant%27s_Causeway#/media/File:Giants_causeway_closeup.jpg), just might catch locals eyes a little, again though, happily run with it anyway 😄

**Comment by Jenya-design** [comment]
Thank you @Nevin243, I'll adjust the rocks

**Comment by Jenya-design** [comment]
@adamj89 @Nevin243 please check the update attached and [on Drive](https://drive.google.com/drive/folders/1Xp4R9JwqlHO0e7RoyhGcqKcmupoObyRU?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/meetup/assets/69306070/759e8540-8461-4f42-b66e-db50d7e00a5d)

**Comment by Nevin243** [comment]
Love it, great work Jenya!
